name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  ci:
    uses: kornsour/gh-automation/.github/workflows/ci.yml@8389ab51e28c3c75507f88009b78bf387ca811b1 # ci.yml pinned 2026-09-06
    with:
      migration-check: true
