name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  ci:
    uses: kornsour/gh-automation/.github/workflows/ci.yml@656f46da71566a02a641be3dcc26e07339b6e689 # ci.yml pinned 2026-09-06
    with:
      migration-check: true
