name: Lockfile
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lockfile:
    uses: kornsour/gh-automation/.github/workflows/lockfile-guard.yml@8389ab51e28c3c75507f88009b78bf387ca811b1 # lockfile-guard.yml pinned 2026-09-06
